# Etapa de compilación
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /app

# Copiar solo los archivos del proyecto principal
COPY proyectoIngSoft.csproj ./
RUN dotnet restore proyectoIngSoft.csproj

# Instalar iTextSharp directamente en el proyecto
RUN dotnet add proyectoIngSoft.csproj package iTextSharp --version 5.5.13.3

# Copiar el resto de los archivos del proyecto
COPY . ./

# Publicar la aplicación (indicando explícitamente el .csproj)
RUN dotnet publish proyectoIngSoft.csproj -c Release -o out

# Etapa de ejecución
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build-env /app/out .

# Nombre del archivo principal a ejecutar
ENV APP_NET_CORE proyectoIngSoft.dll

# Ejecutar la aplicación
CMD ASPNETCORE_URLS=http://*:$PORT dotnet $APP_NET_CORE

