// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyectoIngSoft.Data;

#nullable disable

namespace proyectoIngSoft.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250924202038_NovoMigracion")]
    partial class NovoMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("proyectoIngSoft.Models.Accidente", b =>
                {
                    b.Property<int>("IdAccidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAccidente"));

                    b.Property<int>("DNI")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaIni")
                        .HasColumnType("date");

                    b.Property<string>("NombreComp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAccidente");

                    b.ToTable("t_Accidente");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.Descanso", b =>
                {
                    b.Property<int>("IdDescanso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDescanso"));

                    b.Property<int?>("AccidenteId")
                        .HasColumnType("integer");

                    b.Property<int?>("EnfermedadFamId")
                        .HasColumnType("integer");

                    b.Property<int?>("EnfermedadId")
                        .HasColumnType("integer");

                    b.Property<int?>("FallecimientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaternidadId")
                        .HasColumnType("integer");

                    b.Property<int?>("PaternidadId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDescansoId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("IdDescanso");

                    b.HasIndex("AccidenteId");

                    b.HasIndex("EnfermedadFamId");

                    b.HasIndex("EnfermedadId");

                    b.HasIndex("FallecimientoId");

                    b.HasIndex("MaternidadId");

                    b.HasIndex("PaternidadId");

                    b.HasIndex("TipoDescansoId");

                    b.HasIndex("UserId");

                    b.ToTable("t_Descanso");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.DocumentoMedico", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumento"));

                    b.Property<byte[]>("Archivo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("DescansoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Tamaño")
                        .HasColumnType("bigint");

                    b.HasKey("IdDocumento");

                    b.HasIndex("DescansoId");

                    b.ToTable("DocumentosMedicos");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.Enfermedad", b =>
                {
                    b.Property<int>("IdEnfermedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnfermedad"));

                    b.Property<string>("CentroMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescEnfe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiasDesc")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaIni")
                        .HasColumnType("date");

                    b.Property<string>("NombreMedi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubtipoSol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEnfermedad");

                    b.ToTable("t_Enfermedad");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.EnfermedadFam", b =>
                {
                    b.Property<int>("IdEnfermedadFam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnfermedadFam"));

                    b.Property<string>("CentroMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiaSoli")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaDiag")
                        .HasColumnType("date");

                    b.Property<string>("Medico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreFamiliar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCMP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEnfermedadFam");

                    b.ToTable("t_EnfermedadFamiliar");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.Fallecimiento", b =>
                {
                    b.Property<int>("IdFallec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFallec"));

                    b.Property<DateOnly>("FechaComun")
                        .HasColumnType("date");

                    b.Property<string>("LugarSep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreFallec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Traslado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdFallec");

                    b.ToTable("t_Fallecimiento");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.Maternidad", b =>
                {
                    b.Property<int>("IdMater")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMater"));

                    b.Property<string>("CentroMed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaParto")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaUltM")
                        .HasColumnType("date");

                    b.Property<string>("MedicoT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartoMult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SemanasGest")
                        .HasColumnType("integer");

                    b.HasKey("IdMater");

                    b.ToTable("t_Maternidad");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.Paternidad", b =>
                {
                    b.Property<int>("IdPater")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPater"));

                    b.Property<string>("CentroMed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaComun")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaParto")
                        .HasColumnType("date");

                    b.Property<string>("NombrePareja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoSituacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPater");

                    b.ToTable("t_Paternidad");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.TipoDescanso", b =>
                {
                    b.Property<int>("IdTDescanso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTDescanso"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTDescanso");

                    b.ToTable("t_TiposDescanso");

                    b.HasData(
                        new
                        {
                            IdTDescanso = 1,
                            Nombre = "Enfermedad"
                        },
                        new
                        {
                            IdTDescanso = 2,
                            Nombre = "Maternidad"
                        },
                        new
                        {
                            IdTDescanso = 3,
                            Nombre = "Paternidad"
                        },
                        new
                        {
                            IdTDescanso = 4,
                            Nombre = "Fallecimiento Familiar"
                        },
                        new
                        {
                            IdTDescanso = 5,
                            Nombre = "Enfermedad Familiar"
                        },
                        new
                        {
                            IdTDescanso = 6,
                            Nombre = "Accidente"
                        });
                });

            modelBuilder.Entity("proyectoIngSoft.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CargoLaboral")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmarPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubigeo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdUser");

                    b.ToTable("T_Usuarios");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.ValidarDatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Captcha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Ubigeo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.ToTable("ValidarDatos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("proyectoIngSoft.Models.Descanso", b =>
                {
                    b.HasOne("proyectoIngSoft.Models.Accidente", "Accidente")
                        .WithMany()
                        .HasForeignKey("AccidenteId");

                    b.HasOne("proyectoIngSoft.Models.EnfermedadFam", "EnfermedadFam")
                        .WithMany()
                        .HasForeignKey("EnfermedadFamId");

                    b.HasOne("proyectoIngSoft.Models.Enfermedad", "Enfermedad")
                        .WithMany()
                        .HasForeignKey("EnfermedadId");

                    b.HasOne("proyectoIngSoft.Models.Fallecimiento", "Fallecimiento")
                        .WithMany()
                        .HasForeignKey("FallecimientoId");

                    b.HasOne("proyectoIngSoft.Models.Maternidad", "Maternidad")
                        .WithMany()
                        .HasForeignKey("MaternidadId");

                    b.HasOne("proyectoIngSoft.Models.Paternidad", "Paternidad")
                        .WithMany()
                        .HasForeignKey("PaternidadId");

                    b.HasOne("proyectoIngSoft.Models.TipoDescanso", "TipoDescanso")
                        .WithMany("Descansos")
                        .HasForeignKey("TipoDescansoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyectoIngSoft.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accidente");

                    b.Navigation("Enfermedad");

                    b.Navigation("EnfermedadFam");

                    b.Navigation("Fallecimiento");

                    b.Navigation("Maternidad");

                    b.Navigation("Paternidad");

                    b.Navigation("TipoDescanso");

                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.DocumentoMedico", b =>
                {
                    b.HasOne("proyectoIngSoft.Models.Descanso", "Descanso")
                        .WithMany("DocumentosMedicos")
                        .HasForeignKey("DescansoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descanso");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.Descanso", b =>
                {
                    b.Navigation("DocumentosMedicos");
                });

            modelBuilder.Entity("proyectoIngSoft.Models.TipoDescanso", b =>
                {
                    b.Navigation("Descansos");
                });
#pragma warning restore 612, 618
        }
    }
}
